### ISSUE TITLE
"Failed to load API definition." when using `swagger-config-file`

### ISSUE THREAD

**Issue by RemiBardon** [Legion2/swagger-ui-action#158]
When providing a `swagger-config-file` (for example `swagger-config.yaml`), it's copied in the GitHub Pages branch of the repo. However, the specification file path/URL declared in the config file is not. Therefore, when opening the Swagger UI, one gets "Failed to load API definition." with (for example): 

```error
Fetch error
undefined openapi.yaml
```

## Workaround

Provide a specification file URL, accessible publicly via Swagger UI.

## Proposed solutions

1. Read the config file, find the specification file path, copy it
2. Provide a GitHub Action setting to allow one to provide such a path

**Comment by Legion2** [comment]
When using `swagger-config-file` it's up to the users of the action to copy all the required files, it is out of scope for this action to support all settings in the swagger-config.yaml.
