### ISSUE TITLE
Vunerable swagger-ui package version

### ISSUE THREAD

**Issue by kleozzy** [Legion2/swagger-ui-action#364]
Hey,

Can you please update the package dependencies so that swagger-ui is not within the vulnerable versions ?

**Comment by Legion2** [comment]
There are no Dependabot Alerts for any swagger-ui in this repository, can you provide a reference to the CVE? When Dependabot creates the PR I will merge it and release a patch version.

**Comment by kleozzy** [comment]
Many thanks!

**Comment by Legion2** [comment]
I created a new release with the latest dependabot updates.
