### ISSUE TITLE
Error: No valid Swagger UI releases found

### ISSUE THREAD

**Issue by greyblake** [Legion2/swagger-ui-action#377]
Hi! First of all thank you for maintaining this project.

We'd like to report an issue that we started getting this morning (before it was working well for 2 months).

We have a step in our github workflow whichi is defined as:

```yaml
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          spec-file: ./api.json
          output: ./api_doc
```

It started failing with the following error message:

```
##[debug]Evaluating condition for step: 'Generate Swagger UI'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Generate Swagger UI
##[debug]Loading inputs
##[debug]Loading env
Run Legion2/swagger-ui-action@v1
  with:
    spec-file: ./api.json
    output: ./api_doc
    version: ^3.0.0
  env:
    ENV: ***
    BRANCH: ***
    SSH_AUTH_SOCK: /ssh-agent.sock
/usr/bin/docker exec  e060751954ce1cb27d97366545a427f7649a79229efddcad04bede8f9ff2b5d1 sh -c "cat /etc/*release | grep ^ID"
##[debug]ID=ubuntu
##[debug]ID_LIKE=debian
##[debug]Running JavaScript Action with default external tool: node12
Error: No valid Swagger UI releases found
Error: Error: No valid Swagger UI releases found
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Generate Swagger UI
```

From what I see, the error is originates from this place: https://github.com/Legion2/swagger-ui-action/blob/main/src/swagger-ui-action.ts#L201

It looks like it cannot find the matching release (`3.0.0`), but it's there: https://github.com/swagger-api/swagger-ui/releases/tag/v3.0.0

Thank you in advance.

**Comment by Legion2** [comment]
@indyteo can you please update the PR and use the pagination util provided by the octokit library.
