### ISSUE TITLE
Update to Node.js 16?

### ISSUE THREAD

**Issue by NicoWeio** [Legion2/swagger-ui-action#413]
GitHub left this warning under a recent run of mine:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Legion2/swagger-ui-action, Legion2/swagger-ui-action

**Comment by erikfinnman** [comment]
I see that you have updated to Node 16 - any plans on making a new release with this fix to silence the warning from GitHub when using this action?

**Comment by Legion2** [comment]
I created release 1.2.0 https://github.com/Legion2/swagger-ui-action/releases/tag/v1.2.0
