### ISSUE TITLE
Wrong input name

### ISSUE THREAD

**Issue by MathieuSoysal** [Legion2/swagger-ui-action#477]
## Introduction

Currently the input name for github token is: `GITHUB_TOKEN` but this name are depreciated.

![image](https://github.com/Legion2/swagger-ui-action/assets/43273304/199abbe5-1c62-4ea0-be77-0aa834d45409)

**Comment by Legion2** [comment]
Ok thanks for the heads-up, where does this error message come from?

**Comment by Legion2** [comment]
@MathieuSoysal is this still a problem, the input is defined here https://github.com/Legion2/swagger-ui-action/blob/b3421daa703daf325e545c4b4d7cd77a2100b40a/action.yml#L24 so it should not be an invalid action input

**Comment by Legion2** [comment]
I released a new version where this should work now https://github.com/Legion2/swagger-ui-action/releases/tag/v1.3.0
