### ISSUE TITLE
Any plans to update action to Node.js 20?

### ISSUE THREAD

**Issue by DabrowskiAdamPG** [Legion2/swagger-ui-action#481]
Github warns about deprecated Node.js 16. Any plans to update to v20?

![image](https://github.com/Legion2/swagger-ui-action/assets/124149912/b847bc9f-0229-4fe6-bac2-5a395c6bd62c)

**Comment by Legion2** [comment]
Sure I'm open for PRs.

**Comment by Legion2** [comment]
checkout https://github.com/Legion2/swagger-ui-action/releases/tag/v1.3.0
