### ISSUE TITLE
Please support wildcard character to match multiply files.

### ISSUE THREAD

**Issue by blademainer** [Legion2/swagger-ui-action#70]
`spec-file` just support one file, not support multiply swagger files.

**Comment by Legion2** [comment]
ok how would the ui look like when providing multiple files? Is this already supported by swagger ui?

**Comment by blademainer** [comment]
yeah,  it's support multiple files,  see my swagger docker file: [Dockerfile](https://github.com/pjoc-team/swagger-apis/blob/master/Dockerfile) and the key shell: [run.sh](https://github.com/pjoc-team/swagger-apis/blob/master/run.sh)

**Comment by Legion2** [comment]
You can use your own swagger config file by using `swagger-config-file` or `swagger-config-url` option. `spec-file` is only provided as convenient option so one doesn't have to create the swagger config file for simple setups. For advanced setups you should create the swagger config file by yourself.

I think it is out of scope for this project to reflect the all properties of swagger config in the GitHub Action input.

@blademainer if you think multiple swagger files for a single git repository is a common use case, feel free to open a Pull Request.

**Comment by blademainer** [comment]
> You can use your own swagger config file by using `swagger-config-file` or `swagger-config-url` option. `spec-file` is only provided as convenient option so one doesn't have to create the swagger config file for simple setups. For advanced setups you should create the swagger config file by yourself.
> 
> I think it is out of scope for this project to reflect the all properties of swagger config in the GitHub Action input.
> 
> @blademainer if you think multiple swagger files for a single git repository is a common use case, feel free to open a Pull Request.

Sorry, I'm not good at typescripts, and glad to tell you I'm implemented it by docker, see:  https://github.com/marketplace/actions/swagger-ui

**Comment by Legion2** [comment]
> Sorry, I'm not good at typescripts, and glad to tell you I'm implemented it by docker, see: https://github.com/marketplace/actions/swagger-ui

I can say the same about your shell script which creates the swagger config json.
